### ISSUE TITLE
Changing getActiveTag() to getCachedTag() 

### ISSUE THREAD

**Issue by aminraeisi** [imanghafoori1/laravel-temp-tag#18]
Thanks for the great package!
I was wondering if changing the wording for this will make it more understandable.
Right now we have `getActiveTag()` which returns the tag from the cache but the same active word is also applied when we want to check if the tag `isActive()`. This confused me when I first read `tempTags($user)->getActiveTag('banned')->isActive();` which for me was like get me an `active` tag that is called `'banned'` and then check if it is `active or not`. 
Not sure if that makes sense but wanted to know your thoughts about it 😅. So what I am proposing is changing the `getActiveTag()` to `getCachedTag()`.

**Comment by imanghafoori1** [comment]
`tempTags($user)->getTag('banned')->isActive();`

isActive method is meant to be called when we fetch the tag regardless of its expiration state by `getTag`.

**Comment by aminraeisi** [comment]
> `tempTags($user)->getTag('banned')->isActive();`
> 
> isActive method is meant to be called when we fetch the tag regardless of its expiration state by `getTag`.

What I meant was about the `getActiveTag()` it gets the cached tags not active tags. That's why I said it may be better to name it `getCachedTag()` instead. Anyways, failed attempt from me 😅👍.

**Comment by imanghafoori1** [comment]
The cache expires as soon as the tag is expired. so there is no difference from outside.
